apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: rizaleko/node-boilerplate:3
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: mongodb://mongo-service.default.svc.cluster.local:27017/test
