name: Node Build, Test, Push to Docker Hub, and Deploy to K8S

on:
  push:
    paths:
      - 'hackathon-starter/**'
      - '.github/workfolws/ci-node-boilerplate.yml'

defaults:
  run:
    working-directory: hackathon-starter

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: hackathon-starter
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node-boilerplate:${{ github.run_number }}

  deploy-K8S-node:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GKE_PROJECT }}
      GKE_CLUSTER: apache-flink-cluster-1
      GKE_ZONE: us-central1-c

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure SA.
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # Get the k8s credentials so we can deploy to the cluster
    - name: Set up k8s credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Deploy node App to k8s
      run: |
        sed -i "s/TAG/${{ github.run_number }}/g" k8s/node-deployment.yaml
        kubectl delete -f k8s/
