name: Build, Test, Push to Docker Hub, and Deploy to GKE

on:
  push:
    paths:
      - 'go/**'

defaults:
  run:
    working-directory: go

jobs:
  # build-test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: '1.19.x'
  #     - name: Install dependencies
  #       run: go get .
  #     - name: Build
  #       run: go build -v ./...
  #     - name: Test with the Go CLI
  #       run: go test

  docker-push:
    # needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: go
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go:${{ github.run_number }}
