name: Build, Test, Push to Docker Hub, and Deploy to GKE

on:
  push:
    paths:
      - 'go/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version-file: go.mod

      - name: Build and Test
        run: go build -v ./.. && go test -v ./...

  docker-push:
    needs: build-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go:${{ github.run_number }}
